# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"generate_blobs": "00_data.ipynb",
         "kde_hist": "01_smooth.ipynb",
         "hists_from_nn": "02_makers.ipynb",
         "jax_backend": "02_makers.ipynb",
         "hepdata_like_from_hists": "02_makers.ipynb",
         "histosys_model_from_hists": "02_makers.ipynb",
         "to_bounded_vec": "03_transforms.ipynb",
         "to_bounded": "03_transforms.ipynb",
         "to_inf_vec": "03_transforms.ipynb",
         "to_inf": "03_transforms.ipynb",
         "global_fit": "04_fit.ipynb",
         "constrained_fit": "04_fit.ipynb",
         "expected_CLs": "05_infer.ipynb",
         "Model": "99_models.ipynb",
         "hepdata_like": "99_models.ipynb"}

modules = ["data.py",
           "smooth.py",
           "makers.py",
           "transforms.py",
           "fit.py",
           "infer.py",
           "models.py"]

doc_url = "https://gradhep.github.io/neos/"

git_url = "https://github.com/gradhep/neos/"

def custom_doc_links(name): return None
