# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"init_config": "00_models.ipynb",
         "init_model": "00_models.ipynb",
         "expected_data": "00_models.ipynb",
         "logpdf": "00_models.ipynb",
         "hepdata_like": "00_models.ipynb",
         "Model": "00_models.ipynb",
         "nn_model_maker": "00_models.ipynb",
         "hists_from_nn_three_blobs": "01_makers.ipynb",
         "nn_hepdata_like": "01_makers.ipynb",
         "to_bounded_vec": "02_transforms.ipynb",
         "to_bounded": "02_transforms.ipynb",
         "to_inf_vec": "02_transforms.ipynb",
         "to_inf": "02_transforms.ipynb",
         "get_solvers": "03_fit.ipynb",
         "cls_maker": "04_cls.ipynb"}

modules = ["models.py",
           "makers.py",
           "transforms.py",
           "fit.py",
           "cls.py"]

doc_url = "https://phinate.github.io/neos/"

git_url = "https://github.com/phinate/neos/tree/master/"

def custom_doc_links(name): return None
