# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"generate_blobs": "00_data.ipynb",
         "hists_from_nn": "02_makers.ipynb",
         "jax_backend": "02_makers.ipynb",
         "hepdata_like_from_hists": "02_makers.ipynb",
         "histosys_model_from_hists": "02_makers.ipynb",
         "Model": "99_models.ipynb",
         "hepdata_like": "99_models.ipynb"}

modules = ["data.py",
           "makers.py",
           "models.py"]

doc_url = "https://gradhep.github.io/neos/"

git_url = "https://github.com/gradhep/neos/"

def custom_doc_links(name): return None
