# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"one_hot": "00_nn.ipynb",
         "simple_classifier": "00_nn.ipynb"}

modules = ["nn.py"]

doc_url = "https://phinate.github.io/fullstream/"

git_url = "https://github.com/phinate/fullstream/tree/master/"

def custom_doc_links(name): return None
