# AUTOGENERATED! DO NOT EDIT! File to edit: 02_data.ipynb (unless otherwise specified).

__all__ = ['get_three_blobs']

# Cell
import jax

# Cell
def get_three_blobs(keys=[1, 2, 3],num_points=5000):
    k1, k2, k3 = keys
    sig = jax.random.multivariate_normal(
        jax.random.PRNGKey(k1),
        jax.numpy.asarray([2, 5]),
        jax.numpy.asarray([[1, 0.0], [0.0, 1]]),
        shape=(1, num_points),
    )[0]
    bkg1 = jax.random.multivariate_normal(
        jax.random.PRNGKey(k2),
        jax.numpy.asarray([4, 6]),
        jax.numpy.asarray([[1, 0.6], [0.6, 1]]),
        shape=(1, num_points),
    )[0]
    bkg2 = jax.random.multivariate_normal(
        jax.random.PRNGKey(k3),
        jax.numpy.asarray([5.5, 4.5]),
        jax.numpy.asarray([[1.7, 0.2], [0.2, 1]]),
        shape=(1, num_points),
    )[0]
    return sig, bkg1, bkg2